### ISSUE TITLE
wrapping around longitude is not done right

### ISSUE THREAD

**Issue by myying** [nansencenter/NERSC-HYCOM-CICE#196]
In `pythonlibs/modelgrid/modelgrid/confmap.py` the `pivotp` function has the following code for wrapping around longitude (not the actual earth longitude, but the new longitude in the rotated pole settings, called `lon_n` in the ConformalMapping object)

      # fix for wrap-around
      # western limit in new coordinates can be east of eastern limit (sigh)....
      # in that case di is < 0
      lontmp=numpy.copy(lon_o)
      #
      I=numpy.logical_and(lontmp<self._wlim,self._di>0.)
      lontmp[I]=lontmp[I]+360.
      #
      I=numpy.logical_and(lontmp>self._wlim,self._di<0.)
      lontmp[I]=lontmp[I]+360.
      #
      I=lontmp-self._wlim > 360.
      lontmp[I] = lontmp[I]-360.

This logic if ` lontmp<self._wlim` then `lontmp += 360` is not right. 

It seems that `oldtonew` returns longitude that follows the -180:180 convention (western lon is negative), while we use a 0:360 convention for the grid.ifo. Take an example of wlim=177, elim=182 in grid.info. This means lon_n has minimum of 177, then goes to 180 to the middle of domain, then actually goes from -180 to -178 (which is 182-360) to the right boundary of the domain.  

What needs to be wrapped around is not the points with lat_n < wlim, but rather, those negative lon_n points (-180 to -178). These should be flipped to 180 to 182 so that the lon_n is continuous along the x direction in the domain.

Suggested new logic:

       ##fix wrap-around issue for longitude
       lon_o[np.where(lon_o<0)] += 360.

This should work for both di > 0 (wlim<elim) and di < 0 (wlim>elim), I've tested both scenarios.

If the pivot point is outside the domain, it should still be reflecting the correct distance relative to the domain. For example, if the lon_n is smaller than wlim (falling out of left side of domain), its pivot point index should be negative something in x direction. But the old code returns a very large index (still outside of domain though, so this fortunately didn't impact any DA results I guess).

btw: the pivotp function should have `lat_n, lon_n`  as inputs, but the code reads `def pivotp(self, lat_o, lon_o)` which is confusing.

**Comment by lilleannette** [comment]
Hi,

I changed the code and created a pull request:


Suggested new logic:

   ##fix wrap-around issue for longitude

   lon_o[np.where(lon_o<0)] += 360.

I think probably it should be tested with a couple of routines using the function before it is approved.

I did not include this:

«the pivotp function should have lat_n, lon_n as inputs, but the code reads def pivotp(self, lat_o, lon_o) which is confusing.»

In the pull request, but it can be done.



Annette



Annette Samuelsen
forskningsleder | Research Leader

***@***.*** | +47 932 38 202


Stiftelsen Nansen Senter for Miljø og Fjernmåling
Nansen Environmental and Remote Sensing Center
Jahnebakken 3 | N-5007 Bergen | Norway
***@***.*** | nersc.no<https://nersc.no> | +47 55 20 58 00

[cid:logo_de1c6baf-5da6-4f53-b1e5-34827df1144c.jpg]



Konfidensialitet. Ansvarsfraskrivelse. Informasjonen i denne e-posten er utelukkende ment for bruk av adressaten(e), og kan inneholde konfidensiell informasjon som ikke kan deles uten avsenders skriftlige samtykke.
Notice of confidentiality. Disclaimer. The information contained in this e-mail is intended solely for the use of the addressee(s) and may contain confidential or legally privileged information.
From: Yue (Michael) Ying ***@***.***>
Date: Saturday, 17 June 2023 at 15:47
To: nansencenter/NERSC-HYCOM-CICE ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nansencenter/NERSC-HYCOM-CICE] wrapping around longitude is not done right (Issue #196)

In pythonlibs/modelgrid/modelgrid/confmap.py the pivotp function has the following code for wrapping around longitude (not the actual earth longitude, but the new longitude in the rotated pole settings, called lon_n in the ConformalMapping object)

  # fix for wrap-around

  # western limit in new coordinates can be east of eastern limit (sigh)....

  # in that case di is < 0

  lontmp=numpy.copy(lon_o)

  #

  I=numpy.logical_and(lontmp<self._wlim,self._di>0.)

  lontmp[I]=lontmp[I]+360.

  #

  I=numpy.logical_and(lontmp>self._wlim,self._di<0.)

  lontmp[I]=lontmp[I]+360.

  #

  I=lontmp-self._wlim > 360.

  lontmp[I] = lontmp[I]-360.

This logic if lontmp<self._wlim then lontmp += 360 is not right.

It seems that oldtonew returns longitude that follows the -180:180 convention (western lon is negative), while we use a 0:360 convention for the grid.ifo. Take an example of wlim=177, elim=182 in grid.info. This means lon_n has minimum of 177, then goes to 180 to the middle of domain, then actually goes from -180 to -178 (which is 182-360) to the right boundary of the domain.

What needs to be wrapped around is not the points with lat_n < wlim, but rather, those negative lon_n points (-180 to -178). These should be flipped to 180 to 182 so that the lon_n is continuous along the x direction in the domain.

Suggested new logic:

   ##fix wrap-around issue for longitude

   lon_o[np.where(lon_o<0)] += 360.

This should work for both di > 0 (wlim<elim) and di < 0 (wlim>elim), I've tested both scenarios.

If the pivot point is outside the domain, it should still be reflecting the correct distance relative to the domain. For example, if the lon_n is smaller than wlim (falling out of left side of domain), its pivot point index should be negative something in x direction. But the old code returns a very large index (still outside of domain though, so this fortunately didn't impact any DA results I guess).

btw: the pivotp function should have lat_n, lon_n as inputs, but the code reads def pivotp(self, lat_o, lon_o) which is confusing.
